export const BLOG_POST_FETCH = "BLOG_POST_FETCH";

export const BLOG_POST_LIST_RECEIVED = "BLOG_POST_LIST_RECEIVED";
export const BLOG_POST_LIST_ERROR = "BLOG_POST_LIST_ERROR";

export const BLOG_POST_RECEIVED = "BLOG_POST_RECEIVED";
export const BLOG_POST_ERROR = "BLOG_POST_ERROR";
export const BLOG_POST_UNLOAD = "BLOG_POST_UNLOAD";

export const COMMENTS_FETCHING = "COMMENTS_FETCHING";
export const COMMENTS_RECEIVED = "COMMENTS_RECEIVED";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const COMMENTS_UNLOAD = "COMMENTS_UNLOAD";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FETCHING = "USER_LOGIN_FETCHING";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_SET_ID = "USER_SET_ID";

export const USER_PROFILE_FETCHING = "USER_PROFILE_FETCHING";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
