export const BLOG_POST_FETCH = "BLOG_POST_FETCH";

export const BLOG_POST_LIST_RECEIVED = "BLOG_POST_LIST_RECEIVED";
export const BLOG_POST_LIST_ERROR = "BLOG_POST_LIST_ERROR";
export const BLOG_POST_LIST_UNLOAD = "BLOG_POST_LIST_UNLOAD";
export const BLOG_POST_LIST_SET_PAGE = "BLOG_POST_LIST_SET_PAGE";

export const BLOG_POST_RECEIVED = "BLOG_POST_RECEIVED";
export const BLOG_POST_ERROR = "BLOG_POST_ERROR";
export const BLOG_POST_UNLOAD = "BLOG_POST_UNLOAD";

export const COMMENTS_FETCHING = "COMMENTS_FETCHING";
export const COMMENTS_RECEIVED = "COMMENTS_RECEIVED";
export const COMMENTS_ERROR = "COMMENTS_ERROR";
export const COMMENTS_UNLOAD = "COMMENTS_UNLOAD";
export const COMMENTS_SET_PAGE = "COMMENTS_SET_PAGE";
export const COMMENT_NEW_SUCCESS = "COMMENT_NEW_SUCCESS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FETCHING = "USER_LOGIN_FETCHING";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_SET_ID = "USER_SET_ID";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PROFILE_FETCHING = "USER_PROFILE_FETCHING";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_REGISTER_COMPLETE = "USER_REGISTER_COMPLETE";
